version: '3.8'
services:
  db:
    image: mongo:3.6.18-xenial
    ports:
      - '27017:27017'
  http:
    command: npm run start:dev
    build: .
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - db
